### ISSUE TITLE
Contrast color becomes main color

### ISSUE THREAD

**Issue by mbstrauss** [pughpugh/react-countdown-clock#53]
The first time I run the clock there is a noticeable difference between the main color and the lighter contrast color that defines the countdown. Each time the timer is run the two colors get closer together to the point that after around 5 times they are the same and you cannot see any difference. 

Am I using the control incorrectly?

   <ReactCountdownClock 
                        seconds={this.state.secs}
                        color="blue"
                        alpha={.9}
                        weight={this.props.parameters.containerHeight.container*.2}
                        showMilliseconds="false"
                        onComplete={this.onComplete}
                        size={this.props.parameters.containerHeight.container*.8} />

Thanks

Michael

**Comment by pughpugh** [comment]
Yes you're using it correct, but this is a bug.

In some instances, it appears when the time starts again a new background gets drawn over the old one. Because the background is translucent, they layer over each other and become increasingly opaque over time.

I've a fix for the next version. Thanks for raising this.

**Comment by pughpugh** [comment]
Fixed in 2.2.0
